import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { Resend } from "resend";
import PDFDocument from "pdfkit";
import multer from "multer";
import path from "path";
import fs from "fs";

import connectDB from "./database/db.js";
import Order from "./models/Order.js";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

const resend = new Resend(process.env.RESEND_API_KEY);

app.use(cors());
app.use(express.json());
app.use("/uploads", express.static("uploads"));

connectDB();

const uploadDir = "uploads";

if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir);
}

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, uploadDir);
  },
  filename: (req, file, cb) => {
    const uniqueName = `${Date.now()}-${file.originalname}`;
    cb(null, uniqueName);
  },
});

const upload = multer({ storage });

app.get("/", (req, res) => {
  res.send("LeanFit backend is running");
});

function createOrderId() {
  const date = new Date();
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  const random = Math.floor(1000 + Math.random() * 9000);

  return `LF-${y}${m}${d}-${random}`;
}

function createPlanPDF(userData, planText, orderId) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    doc.fontSize(26).fillColor("#16a34a").text("LEANFIT", {
      align: "center",
    });

    doc
      .moveDown(0.5)
      .fontSize(16)
      .fillColor("#111827")
      .text("Personalized Fitness Plan", { align: "center" });

    doc
      .moveDown(0.5)
      .fontSize(11)
      .fillColor("#6b7280")
      .text(`Order ID: ${orderId}`, { align: "center" });

    doc.moveDown(2);

    doc.fontSize(13).fillColor("#111827");
    doc.text(`Order ID: ${orderId}`);
    doc.text(`Name: ${userData.name || "Member"}`);
    doc.text(`Mobile: ${userData.mobile || "Not specified"}`);
    doc.text(`Email: ${userData.email || "Not specified"}`);
    doc.text(`Selected Plan: ${userData.selectedPlan || "Not selected"}`);
    doc.text(`Amount: Rs.${userData.selectedPrice || "0"}`);
    doc.text(`Goal: ${userData.goal || "Not specified"}`);
    doc.text(`Current Weight: ${userData.weight || "Not specified"} kg`);
    doc.text(`Target Weight: ${userData.targetWeight || "Not specified"} kg`);

    doc.moveDown(1.5);

    doc
      .fontSize(16)
      .fillColor("#16a34a")
      .text("Plan Details", { underline: true });

    doc.moveDown(1);

    doc.fontSize(11).fillColor("#111827").text(planText, {
      align: "left",
      lineGap: 5,
    });

    doc.moveDown(2);

    doc
      .fontSize(10)
      .fillColor("#6b7280")
      .text(
        "Generated by LeanFit. This is a fitness guidance document, not medical advice.",
        { align: "center" }
      );

    doc.end();
  });
}

app.post("/api/generate-plan", upload.single("paymentScreenshot"), async (req, res) => {
  try {
    const userData = JSON.parse(req.body.userData);
    const orderId = createOrderId();

    const paymentScreenshot = req.file ? `/uploads/${req.file.filename}` : "";

    const plan = `
USER SUMMARY
Order ID: ${orderId}
Name: ${userData.name || "Member"}
Goal: ${userData.goal || "Not specified"}
Current Weight: ${userData.weight || "Not specified"} kg
Target Weight: ${userData.targetWeight || "Not specified"} kg

DAILY TARGET
Calories: 2500 kcal
Protein: 160g
Carbs: 280g
Fat: 70g

ONE-DAY DIET PLAN
Breakfast:
Oats with milk OR 3 eggs with roti.

Lunch:
Rice with chicken curry OR dal with rice.

Snack:
Banana with groundnuts OR curd rice.

Dinner:
Roti with paneer OR fish curry with rice.

FOOD ALTERNATIVES
Chicken can be replaced with eggs, paneer, fish, dal or chana.
Rice can be replaced with roti, oats, poha, idli or dosa.

WORKOUT PLAN
5 days strength training per week.
Focus on progressive overload, proper form and recovery.

LIFESTYLE TIPS
Sleep 7-8 hours daily.
Drink 3L water daily.
Track meals consistently.
Check weight weekly.

FINAL REMINDER
This is a sample personalized plan. Adjustments may be required based on progress.
`;

    const pdfBuffer = await createPlanPDF(userData, plan, orderId);

    const isLeanPro = userData.selectedPlan === "Lean Pro Membership";

    const accessStartDate = isLeanPro ? new Date() : null;
    const accessEndDate = isLeanPro
      ? new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
      : null;

    await Order.create({
      orderId,
      name: userData.name || "",
      email: userData.email || "",
      mobile: userData.mobile || "",
      goal: userData.goal || "",
      weight: Number(userData.weight) || 0,
      targetWeight: Number(userData.targetWeight) || 0,
      selectedPlan: userData.selectedPlan || "",
      selectedPrice: Number(userData.selectedPrice) || 0,
      status: "Pending",
      pdfSent: true,
      dashboardAccess: isLeanPro,
      accessStartDate,
      accessEndDate,
      membershipStatus: isLeanPro ? "Active" : "Not Applicable",
      paymentScreenshot,
    });

    await resend.emails.send({
      from: "LeanFit <onboarding@resend.dev>",
      to: process.env.ADMIN_EMAIL,
      subject: `New LeanFit Order - ${orderId} - ${
        userData.selectedPlan || "Plan"
      } - ${userData.name || "Customer"}`,
      html: `
        <h2>New LeanFit Order</h2>
        <p><strong>Order ID:</strong> ${orderId}</p>
        <p><strong>Name:</strong> ${userData.name || "Not specified"}</p>
        <p><strong>Email:</strong> ${userData.email || "Not specified"}</p>
        <p><strong>Mobile:</strong> ${userData.mobile || "Not specified"}</p>
        <p><strong>Plan:</strong> ${userData.selectedPlan || "Not selected"}</p>
        <p><strong>Amount:</strong> Rs.${userData.selectedPrice || "0"}</p>
        <p><strong>Goal:</strong> ${userData.goal || "Not specified"}</p>
        ${
          paymentScreenshot
            ? `<p><strong>Payment Screenshot:</strong> http://127.0.0.1:${PORT}${paymentScreenshot}</p>`
            : "<p><strong>Payment Screenshot:</strong> Not uploaded</p>"
        }
        <p>The PDF plan is attached.</p>
      `,
      attachments: [
        {
          filename: `${orderId}_${userData.name || "LeanFit"}_Plan.pdf`,
          content: pdfBuffer,
        },
      ],
    });

    res.json({
      success: true,
      orderId,
      plan,
      paymentScreenshot,
      message: "Order saved, screenshot uploaded, PDF emailed to admin",
    });
  } catch (error) {
    console.error("Order error:", error);

    res.status(500).json({
      success: false,
      message: error.message || "Order failed",
    });
  }
});

app.get("/api/orders", async (req, res) => {
  try {
    const orders = await Order.find().sort({ createdAt: -1 });

    res.json({
      success: true,
      orders,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Unable to fetch orders",
    });
  }
});

app.patch("/api/orders/:orderId/status", async (req, res) => {
  try {
    const { orderId } = req.params;
    const { status } = req.body;

    const order = await Order.findOneAndUpdate(
      { orderId },
      { status },
      { new: true }
    );

    if (!order) {
      return res.status(404).json({
        success: false,
        message: "Order not found",
      });
    }

    res.json({
      success: true,
      order,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Unable to update order status",
    });
  }
});

app.listen(PORT, () => {
  console.log(`LeanFit backend running on port ${PORT}`);
});