import { useState } from "react";
import PasswordInput from "./PasswordInput";
const API_URL=(import.meta.env.VITE_API_URL||"https://leanfit.onrender.com").replace(/\/$/,"");
function UserProfile({ setPage }) {
 const saved=JSON.parse(localStorage.getItem("leanfitCustomer")||"null");
 const [form,setForm]=useState({name:saved?.name||"",email:saved?.email||"",mobile:saved?.mobile||"",currentPassword:"",newPassword:"",confirmPassword:""});
 const [message,setMessage]=useState(""); const [type,setType]=useState(""); const [loading,setLoading]=useState(false);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const request=async(path,body)=>{const token=localStorage.getItem("leanfitToken"); const res=await fetch(`${API_URL}${path}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(body)}); const data=await res.json(); if(!res.ok||!data.success) throw new Error(data.message||"Update failed"); return data;};
 const saveProfile=async()=>{setLoading(true);setMessage("");try{const clean=form.mobile.replace(/\D/g,"");if(clean.length!==10)throw new Error("Enter a valid 10-digit mobile number.");const data=await request("/api/customer/profile",{name:form.name,email:form.email,mobile:clean});localStorage.setItem("leanfitCustomer",JSON.stringify(data.customer));setMessage("Profile updated successfully.");setType("success");}catch(e){setMessage(e.message);setType("error");}finally{setLoading(false)}};
 const changePassword=async()=>{setLoading(true);setMessage("");try{if(form.newPassword.length<6)throw new Error("New password must contain at least 6 characters.");if(form.newPassword!==form.confirmPassword)throw new Error("New passwords do not match.");await request("/api/customer/password",{currentPassword:form.currentPassword,newPassword:form.newPassword});setForm({...form,currentPassword:"",newPassword:"",confirmPassword:""});setMessage("Password changed successfully.");setType("success");}catch(e){setMessage(e.message);setType("error");}finally{setLoading(false)}};
 if(!saved) return <main className="page"><section className="card"><h2>Please login first.</h2><button className="primary-btn" onClick={()=>setPage("login")}>Customer Login</button></section></main>;
 return <main className="profile-page"><header className="simple-header"><img src="/leanfit-logo.png" alt="LeanFit" className="simple-logo"/><button className="secondary-btn" onClick={()=>setPage("customer-portal")}>Back to Portal</button></header><section className="profile-grid">
 <article className="profile-card"><p className="brand-label">ACCOUNT</p><h2>Profile details</h2><label>Full Name</label><input name="name" value={form.name} onChange={change}/><label>Email ID</label><input name="email" type="email" value={form.email} onChange={change}/><label>Mobile Number</label><input name="mobile" inputMode="numeric" value={form.mobile} onChange={change}/><button className="primary-btn full-btn" disabled={loading} onClick={saveProfile}>{loading?"Saving...":"Save Profile"}</button></article>
 <article className="profile-card"><p className="brand-label">SECURITY</p><h2>Change password</h2><label>Current Password</label><PasswordInput name="currentPassword" value={form.currentPassword} onChange={change}/><label>New Password</label><PasswordInput name="newPassword" value={form.newPassword} onChange={change}/><label>Confirm New Password</label><PasswordInput name="confirmPassword" value={form.confirmPassword} onChange={change}/><button className="secondary-btn full-btn" disabled={loading} onClick={changePassword}>{loading?"Updating...":"Change Password"}</button></article>
 </section>{message&&<p className={`profile-message ${type}`}>{message}</p>}</main>;
}
export default UserProfile;
