import PDFDocument from "pdfkit";

export function createPlanPDF(userData, planText, orderId) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 50,
    });

    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));

    doc.on("end", () => {
      resolve(Buffer.concat(buffers));
    });

    doc.on("error", reject);

    doc
      .fontSize(26)
      .fillColor("#16a34a")
      .text("LEANFIT", {
        align: "center",
      });

    doc.moveDown();

    doc
      .fontSize(18)
      .fillColor("#111827")
      .text("Personalized Fitness Plan", {
        align: "center",
      });

    doc.moveDown();

    doc
      .fontSize(12)
      .fillColor("#6b7280")
      .text(`Order ID: ${orderId}`);

    doc.text(`Name: ${userData.name || ""}`);
    doc.text(`Email: ${userData.email || ""}`);
    doc.text(`Mobile: ${userData.mobile || ""}`);
    doc.text(`Goal: ${userData.goal || ""}`);
    doc.text(`Current Weight: ${userData.weight || ""} kg`);
    doc.text(`Target Weight: ${userData.targetWeight || ""} kg`);
    doc.text(`Plan: ${userData.selectedPlan || ""}`);
    doc.text(`Amount: ₹${userData.selectedPrice || 0}`);

    doc.moveDown();

    doc
      .fontSize(18)
      .fillColor("#16a34a")
      .text("Your Personalized Plan");

    doc.moveDown();

    doc
      .fontSize(11)
      .fillColor("#111827")
      .text(planText, {
        lineGap: 5,
      });

    doc.moveDown(2);

    doc
      .fontSize(10)
      .fillColor("#6b7280")
      .text(
        "Generated by LeanFit AI. This plan is intended for general fitness guidance and is not medical advice.",
        {
          align: "center",
        }
      );

    doc.end();
  });
}